version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: next
    versions:
    - 10.0.6
  - dependency-name: husky
    versions:
    - 4.3.7
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.12.0
